import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import DappOverview from "@/components/home/DappOverview";
import Navbar from "@/components/shared/Navbar/Navbar";
import CreateWalletWrapper from "@/components/createWalletPage/CreateWalletWrapper";
import { useRecoilValue } from "recoil";
import { isWalletCreatedState } from "@/shared/recoil";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function CreateWallet() {
  const walletCreated = useRecoilValue<boolean>(isWalletCreatedState);
  const [iswalletcreated, setIswalletcreated] = useState<boolean>(false);
  useEffect(() => {
    setIswalletcreated(walletCreated);
  }, [walletCreated]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <CreateWalletWrapper walletCreated={iswalletcreated} />
      </main>
    </>
  );
}
