import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import DappOverview from "@/components/home/DappOverview";
import Navbar from "@/components/shared/Navbar/Navbar";
import WalletWrapper from "@/components/walletPage/WalletWrapper/WalletWrapper";
import RecoveryWallet from "@/components/walletPage/RecoveryWallet/RecoveryWallet";

const inter = Inter({ subsets: ["latin"] });

export default function Wallet() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <RecoveryWallet />
      </main>
    </>
  );
}
