"use client";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import DappOverview from "@/components/home/DappOverview";
import Navbar from "@/components/shared/Navbar/Navbar";
import WalletWrapper from "@/components/walletPage/WalletWrapper/WalletWrapper";
import { useRecoilValue } from "recoil";
import { useEffect, useState } from "react";
import { getFromStorage } from "@/shared/localstorage";

const inter = Inter({ subsets: ["latin"] });

export default function Wallet() {
  const isUnLocked = getFromStorage("wallet-unlocked");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <WalletWrapper isUnLocked={isUnLocked} />
      </main>
    </>
  );
}
